language: python
python:
  - "3.6"

install:
  - pip install -e . -r ./requirements-dev.txt

script:
  - pytest --cov=ngi-analysis-manager tests/

after_success:
  - codecov

notifications:
    email: false