language: python
python:
  - "3.6"

install:
  - pip install -r ./requirements-dev.txt

script:
  - python -m pytest --cov=ngi-analysis-manager tests/

after_success:
  - codecov

notifications:
    email: false